language: python
python:
- '2.7'
install:
- python setup.py install
- pip install -r requirements.txt
- pip install coveralls
script:
  coverage run --source=pyiso setup.py test
deploy:
  provider: pypi
  user: Anna.Schneider
  password:
    secure: SHHMXoR9TEeWyarMLSoPEP1MFCOawTAgFTaBuLAMu7nGVk0+HbwD78MiAd6k7LaSYj+huL8/B6JKWgY36b2liS33EzJUkaMtS9vt/RzTZUJix/rJepZ4d+6e+rAr+DL/ulCUGot8ILK6vO0S1BzlcQYyXJsc01LzngFDcVWY6sA=
  on:
    tags: true
    repo: WattTime/pyiso
after_success:
  - coveralls